Caviardage/Models/ErrorViewModel.cs
namespace Caviardage.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Caviardage/Controllers/CaviardageController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using Tesseract;
using iTextSharp.text;
using iTextSharp.text.pdf;

namespace Caviardage.Controllers
{
    public class CaviardageController : Controller
    {
        public ActionResult UploadPassport()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ProcessPassport(IFormFile passportImage)
        {
            string outputPath = @"C:\Users\User\Documents\ziedCaviarde.pdf"; // Remplacez par le chemin de sortie souhaité
            if (passportImage != null && passportImage.Length > 0)
            {
                try
                {
                    using (var engine = new TesseractEngine(@"./tessdata", "eng", EngineMode.Default))
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            passportImage.CopyTo(memoryStream);
                            memoryStream.Position = 0; // Reset the position to the beginning of the stream

                            var doc = new Aspose.Words.Document(memoryStream);



                           doc.Save($"Output.tiff");


                            using (var img = Pix.LoadFromFile($"Output.tiff"))
                            {
                                using (var page = engine.Process(img))
                                {
                                    // Récupération du texte complet
                                    string texteComplet = page.GetText();
                                    texteComplet = texteComplet.Replace("Evaluation Only. Created with Aspose.Words. Copyright 2003-2024 Aspose Pty Ltd.", "");
                                    texteComplet = texteComplet.Replace("Created with an evaluation copy of Aspose.Words. To discover the full versions of our APIs\r\nplease ttps://products.aspose.com/words/", "");

                                    // Remplacer les informations sensibles par des étoiles
                                    string texteAffiche = RedigerPII(texteComplet);

                                    ViewBag.MyString = texteAffiche;

                                    iTextSharp.text.Document documentPdf = new iTextSharp.text.Document(PageSize.A4);

                                    // Création du fichier de sortie
                                    PdfWriter.GetInstance(documentPdf, new FileStream(outputPath, FileMode.Create));

                                    // Ouverture du document
                                    documentPdf.Open();


                                    // Ajout du texte au document
                                    documentPdf.Add(new iTextSharp.text.Paragraph(texteAffiche));
                                    // Fermeture du document
                                    documentPdf.Close();



                                  
                                }
                            }
                        }
                    }
                }
                catch
                {
                    ViewBag.Error = "An error occurred during processing. Please try again.";
                }
            }
            else
            {
                ViewBag.Error = "Please upload an image.";
            }
           

            return View("AffichageResultat");
        }
        static string RedigerPII(string texte)
        {
            // Remplacer les informations sensibles par des étoiles
            string texteRedige = Regex.Replace(texte, @"\b(?:\d{3}-\d{3}-\d{3}|\d{4}-\d{4}-\d{4}-\d{4}|[A-Z][a-z]+)\b", "***");

            return texteRedige;
        }

    }
}

Caviardage/Controllers/HomeController.cs
using Caviardage.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Caviardage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Caviardage/Views/Caviardage/AffichageResultat.cshtml
@model string

<!DOCTYPE html>
<html>
<head>
    <title>Document Word</title>
</head>
<body>
    <h1>Contenu du document Word :</h1>
    <pre>@ViewBag.MyString</pre>
</body>
</html>

Caviardage/Views/Caviardage/UploadPassport.cshtml
@{
    ViewBag.Title = "UploadPassport";
}

<h2>Charger le document a caviarder:</h2>

@using (Html.BeginForm("ProcessPassport", "Caviardage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="passportImage" />
    <input type="submit" value="Process" />
}

Caviardage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Caviardage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Caviardage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Caviardage.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Caviardage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Caviardage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>